name: Take screenshots

on:
  workflow_dispatch:
  schedule:
    - cron:  '5 20 * * *'

jobs:
  take_screenshots:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Cache Playwright browsers
      uses: actions/cache@v2
      with:
        path: ~/.cache/ms-playwright/
        key: ${{ runner.os }}-browsers
    - name: Check scripts are executable
      run: |
        ls -lah
      shell: bash
    - name: Install dependencies
      run: ./install.sh
      shell: bash
    - name: Take screenshot
      run: ./run.sh
      shell: bash
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git commit -m "Latest: ${{ env.timestamp }}"
        git pull --rebase
        git push
